# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'AgTrialPlanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Core dependencies
  pod 'Alamofire', '~> 5.7'
  pod 'SQLite.swift', '~> 0.14.0'
  pod 'KeychainAccess', '~> 4.2.2'
  
  # Authentication
  pod 'GoogleSignIn', '~> 7.0'
  pod 'MSAL', '~> 1.2.0'
  
  # UI components
  pod 'SDWebImage', '~> 5.18.0'
  pod 'lottie-ios', '~> 4.3.0'
  
  # Maps and location
  pod 'MapboxMaps', '~> 10.16.0'
  pod 'MapboxNavigation', '~> 2.16.0'
  
  # Utilities
  pod 'SwiftLint', '~> 0.53.0'
  pod 'R.swift', '~> 7.3.0'
  pod 'Swinject', '~> 2.8.0'
  pod 'SwiftyBeaver', '~> 1.9.0'

  target 'AgTrialPlannerTests' do
    inherit! :search_paths
    # Testing dependencies
    pod 'Quick', '~> 7.0.0'
    pod 'Nimble', '~> 12.0.0'
    pod 'OHHTTPStubs/Swift', '~> 9.1.0'
  end

  target 'AgTrialPlannerUITests' do
    # UI Testing dependencies
    pod 'SnapshotTesting', '~> 1.11.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      
      # Enable code signing for frameworks
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      
      # Enable memory safety features where available
      if config.name == 'Debug'
        config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = '$(inherited) DEBUG ENABLE_MEMORY_SAFETY_CHECKS'
      end
    end
  end
end