version: 0.2

# AWS CodeBuild configuration for the Agricultural Trial Plot Planning app
# This buildspec auto-detects and adapts to the appropriate mode (demo or database)

env:
  variables:
    # Set this to true to enable demo login mode
    ALLOW_DEMO_LOGIN: "true"
    # Uncomment the line below if you want to use a database
    # DATABASE_URL: "your-database-url-here"

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - echo "🔧 Installing dependencies..."
      # IMPORTANT: Using npm install instead of npm ci since package-lock.json is gitignored
      - npm install --no-package-lock
      
      # Only install database-specific packages if DATABASE_URL is set
      - |
        if [ ! -z "$DATABASE_URL" ]; then
          echo "📦 Installing database-specific packages..."
          npm install @auth/prisma-adapter@latest --no-package-lock
          npm run prisma:generate
        else
          echo "ℹ️ Running in demo-only mode (no database)"
        fi

  build:
    commands:
      - echo "🏗️ Building application..."
      # Choose the appropriate build command based on whether DATABASE_URL is set
      - |
        if [ ! -z "$DATABASE_URL" ]; then
          echo "🏗️ Building with database support..."
          npm run build
        else
          echo "🏗️ Building in demo-only mode..."
          ALLOW_DEMO_LOGIN=true npm run build:demo
        fi

  post_build:
    commands:
      - echo "✅ Build completed successfully"

artifacts:
  files:
    - next.config.js
    - package.json
    - .next/**/*
    - public/**/*
    - node_modules/**/*
    - .env
  base-directory: .
  discard-paths: no